"use client";

import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Lang = "ar" | "fr";

interface LangCtx {
  lang: Lang;
  t: (key: string) => string;
  setLang: (l: Lang) => void;
}

const translations: Record<Lang, Record<string, string>> = {
  ar: {
    // General
    appName: "نظام إدارة كراء السيارات",
    appDesc: "نظام احترافي لإدارة وكالة كراء السيارات",
    dashboard: "لوحة القيادة",
    clients: "العملاء",
    cars: "السيارات",
    contracts: "العقود",
    payments: "المدفوعات",
    maintenance: "الصيانة",
    reports: "التقارير",
    settings: "الإعدادات",

    // Actions
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    search: "بحث",
    confirm: "تأكيد",
    back: "عودة",
    actions: "الإجراءات",
    saving: "جاري الحفظ...",
    update: "تحديث",
    save_error: "خطأ أثناء الحفظ",
    delete_error: "خطأ أثناء الحذف",

    // Status
    status: "الحالة",
    active: "نشط",
    completed: "منتهي",
    cancelled: "ملغي",
    available: "متاحة",
    rented: "مؤجرة",
    maintenance_s: "صيانة",
    retired: "متقاعدة",

    // Dashboard
    dashboard_title: "لوحة القيادة",
    dashboard_desc: "نظرة عامة على نشاط الوكالة",
    active_contracts: "العقود النشطة",
    available_cars: "السيارات المتاحة",
    monthly_revenue: "إيرادات الشهر",
    total_clients: "إجمالي العملاء",
    recent_contracts: "آخر العقود",
    view_all: "عرض الكل",
    quick_actions: "إجراءات سريعة",
    no_contracts: "لا توجد عقود حالياً",
    alerts: "التنبيهات",
    no_alerts: "لا توجد تنبيهات حالياً",

    // Login
    login_title: "تسجيل الدخول إلى لوحة التحكم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    login_anonymous: "دخول كزائر (بدون حساب)",
    no_account: "ليس لديك حساب؟",
    create_account: "إنشاء حساب جديد",
    or: "أو",

    // Register
    register_title: "إنشاء حساب جديد",
    register: "إنشاء الحساب",
    confirm_password: "تأكيد كلمة المرور",
    have_account: "لديك حساب بالفعل؟",

    // Clients
    clients_title: "العملاء",
    clients_desc: "إدارة العملاء",
    add_client: "إضافة عميل",
    edit_client: "تعديل العميل",
    search_client: "بحث عن عميل...",
    no_clients: "لم يتم العثور على عميل",
    full_name: "الاسم الكامل",
    phone: "رقم الهاتف",
    cin: "رقم البطاقة",
    cin_expiry: "تاريخ انتهاء البطاقة",
    driver_license: "رخصة السياقة",
    address: "العنوان",
    notes: "ملاحظات",
    name: "الاسم",
    client_updated: "تم تحديث العميل",
    client_added: "تمت إضافة العميل بنجاح",
    client_deleted: "تم حذف العميل",
    confirm_delete_client: "هل أنت متأكد من حذف هذا العميل؟",
    client_detail_desc: "تفاصيل العميل",
    no_client_contracts: "لا توجد عقود لهذا العميل",
    no_client_payments: "لا توجد مدفوعات لهذا العميل",

    // Cars
    cars_title: "السيارات",
    cars_desc: "إدارة أسطول السيارات",
    add_car: "إضافة سيارة",
    edit_car: "تعديل السيارة",
    search_car: "بحث عن سيارة...",
    no_cars: "لم يتم العثور على سيارة",
    brand: "العلامة",
    model: "الطراز",
    year: "السنة",
    plate: "رقم اللوحة",
    chassis: "رقم الهيكل",
    color: "اللون",
    fuel: "الوقود",
    transmission: "ناقل الحركة",
    seats: "المقاعد",
    doors: "الأبواب",
    price_per_day: "السعر/اليوم",
    price_per_week: "السعر/الأسبوع",
    price_per_month: "السعر/الشهر",
    deposit: "التأمين",
    insurance: "انتهاء التأمين",
    inspection: "الفحص الفني",
    all_status: "جميع الحالات",
    gasoline: "بنزين",
    diesel: "ديزل",
    electric: "كهربائي",
    hybrid: "هجين",
    manual: "يدوي",
    automatic: "أوتوماتيكي",
    car_updated: "تم تحديث السيارة",
    car_added: "تمت إضافة السيارة بنجاح",
    car_deleted: "تم حذف السيارة",
    confirm_delete_car: "هل أنت متأكد من حذف هذه السيارة؟",
    example_brand: "مثال: رونو",
    example_model: "مثال: كليو 4",
    dates: "التواريخ",

    // Contracts
    contracts_title: "العقود",
    contracts_desc: "إدارة عقود الكراء",
    new_contract: "عقد جديد",
    no_contracts_found: "لم يتم العثور على عقد",
    client: "العميل",
    vehicle: "السيارة",
    period: "الفترة",
    amount: "المبلغ",
    date: "التاريخ",
    days: "أيام",
    complete: "إنهاء",
    start_date: "تاريخ البداية",
    end_date: "تاريخ النهاية",
    return_date: "تاريخ الإرجاع",
    rental_days: "أيام الكراء",
    total_amount: "المبلغ الإجمالي",
    deposit_returned: "تم إرجاع التأمين",
    cancel_contract: "إلغاء العقد",
    edit_contract: "تعديل العقد",

    // Payments
    payments_title: "المدفوعات",
    payments_desc: "متتبع المدفوعات والتأمينات",
    add_payment: "تسجيل دفعة",
    no_payments: "لم يتم العثور على دفعة",
    method: "طريقة الدفع",
    type: "النوع",
    ref_contract: "رقم العقد",
    cash: "نقداً",
    card: "بطاقة بنكية",
    transfer: "تحويل بنكي",
    payment_type: "دفعة",
    deposit_type: "تأمين",
    return_type: "استرجاع",

    // Maintenance
    maintenance_title: "الصيانة",
    maintenance_desc: "إدارة صيانة السيارات",
    add_maintenance: "إضافة صيانة",
    edit_maintenance: "تعديل الصيانة",
    no_maintenance: "لم يتم العثور على صيانة",
    car_name: "اسم السيارة",
    maintenance_type: "نوع الصيانة",
    cost: "التكلفة",
    garage: "الكراج",
    next_maintenance: "الصيانة القادمة",
    description: "الوصف",

    // Reports
    reports_title: "التقارير",
    reports_desc: "إحصائيات وتحليلات",
    total_revenue: "إجمالي الإيرادات",
    total_payments: "إجمالي المدفوعات",
    monthly_revenue_chart: "الإيرادات الشهرية",
    monthly_payments_chart: "المدفوعات الشهرية",
    fleet_status: "حالة الأسطول",
    top_clients: "أفضل العملاء",
    export_csv: "تصدير CSV",

    // Settings
    settings_title: "الإعدادات",
    settings_desc: "إعدادات النظام والشركة",
    company_info: "معلومات الشركة",
    company_name: "اسم الشركة",
    company_phone: "رقم الهاتف",
    company_email: "البريد الإلكتروني",
    company_address: "العنوان",
    tax_rate: "نسبة الضريبة (%)",
    currency: "العملة",
    late_fee: "غرامة التأخير (اليوم)",
    save_settings: "حفظ الإعدادات",
    database: "قاعدة البيانات",
    connected: "متصل بـ Firebase بنجاح",
    version: "الإصدار",
    mode: "الوضع",
    production: "إنتاج",
    deployment: "النشر",

    // Car detail
    car_info: "المعلومات",
    pricing: "الأسعار",
    per_day: "اليوم",
    per_week: "الأسبوع",
    per_month: "الشهر",
    maintenance_history: "سجل الصيانة",
    contract_history: "سجل العقود",
    no_maintenance_records: "لا توجد سجلات صيانة",
    no_contract_history: "لا توجد عقود سابقة",
    car_not_found: "السيارة غير موجودة",
    back_to_list: "العودة إلى القائمة",

    // Client detail
    client_not_found: "العميل غير موجود",
    client_contracts: "العقود",
    client_payments: "المدفوعات",

    // Contract detail
    contract_detail: "تفاصيل العقد",
    contract_not_found: "العقد غير موجود",
    contract_payments: "المدفوعات",

    // Settings
    language: "اللغة",
    arabic: "العربية",
    french: "الفرنسية",

    // Sidebar
    appSubtitle: "كراء السيارات",
    light_mode: "الوضع النهاري",
    dark_mode: "الوضع الليلي",
    logout: "تسجيل الخروج",
    activity_log: "سجل النشاط",
    expenses: "المصروفات",
    fleet: "الأسطول",
    loyalty: "برنامج الولاء",

    // Register
    register_desc: "سجل للدخول إلى نظام الكراء",

    // Errors
    error_occurred: "حدث خطأ",
    error_login_generic: "حدث خطأ أثناء تسجيل الدخول",
    error_user_not_found: "البريد الإلكتروني غير مسجل",
    error_wrong_password: "كلمة المرور غير صحيحة",
    error_invalid_credential: "بريد إلكتروني أو كلمة مرور غير صحيحة",
    error_invalid_email: "البريد الإلكتروني غير صالح",
    error_too_many_requests: "تم تجاوز عدد المحاولات، حاول لاحقاً",
    error_password_mismatch: "كلمتا المرور غير متطابقتين",
    error_password_too_short: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    error_firebase_auth_not_initialized: "Firebase Auth غير مهيأ",
    error_email_in_use: "البريد الإلكتروني مستعمل بالفعل",
    error_weak_password: "كلمة المرور ضعيفة جداً",
    error_operation_not_allowed: "تسجيل المستخدمين غير مفعل في Firebase",

    // Dashboard extras
    in_maintenance: "قيد الصيانة",
    this_month: "هذا الشهر",
    manage_clients: "إدارة العملاء",
    manage_cars: "إدارة السيارات",
    insurance_expiring: "تأمين السيارة سينتهي قريباً",
    insurance_expired: "تأمين السيارة منتهي",
    inspection_expiring: "الفحص الفني للسيارة سينتهي قريباً",
    inspection_expired: "الفحص الفني للسيارة منتهي",
    contract_overdue: "العقد متأخر عن موعد الإرجاع",

    // Settings extras
    settings_saved: "تم حفظ الإعدادات بنجاح",
    settings_save_error: "خطأ أثناء حفظ الإعدادات",
    firebase_project: "مشروع Firebase",
    not_specified: "غير محدد",
    company_name_placeholder: "وكالة كراء السيارات",
    company_name_required: "اسم الشركة مطلوب",
    deploy_to_vercel: "لنشر التطبيق على Vercel:",
    deploy_step_1: "ارفع المشروع إلى GitHub",
    deploy_step_2: "اربط Vercel بمستودع GitHub",
    deploy_step_3: "أضف متغيرات Firebase",
    deploy_step_4: "انشر!",
    env_copied: "تم نسخ المتغيرات",
    copy_env_vars: "نسخ متغيرات البيئة",

    // Contract extras
    contract_created: "تم إنشاء العقد بنجاح",
    contract_create_error: "خطأ أثناء إنشاء العقد",
    contract_completed: "تم إنهاء العقد بنجاح",
    contract_updated: "تم تحديث العقد بنجاح",
    contract_update_error: "خطأ أثناء تحديث العقد",
    contract_cancelled: "تم إلغاء العقد بنجاح",
    contract_cancel_error: "خطأ أثناء إلغاء العقد",
    contract_complete_error: "خطأ أثناء إنهاء العقد",
    contract_not_found_desc: "العقد المطلوب غير موجود",
    contract_info: "معلومات العقد",
    complete_contract: "إنهاء العقد",
    no_payments_for_contract: "لا توجد مدفوعات لهذا العقد",
    cancel_contract_confirm: "هل أنت متأكد من إلغاء هذا العقد؟",
    select_client: "اختر عميلاً",
    select_car: "اختر سيارة",
    create_contract: "إنشاء العقد",
    deposit_returned_yes: "نعم",
    deposit_returned_no: "لا",

    // Payment extras
    payment_updated: "تم تحديث الدفعة",
    payment_added: "تمت إضافة الدفعة",
    delete_payment_confirm: "هل أنت متأكد من حذف هذه الدفعة؟",
    payment_deleted: "تم حذف الدفعة",
    edit_payment: "تعديل الدفعة",
    new_payment: "دفعة جديدة",
    client_name: "اسم العميل",

    // Maintenance extras
    done: "منفذة",
    scheduled: "مجدولة",
    maintenance_updated: "تم تحديث الصيانة",
    maintenance_added: "تمت إضافة الصيانة",
    delete_maintenance_confirm: "هل أنت متأكد من حذف هذه الصيانة؟",
    maintenance_deleted: "تم حذف الصيانة",
    search_maintenance: "بحث عن صيانة...",
    select_type: "اختر النوع",
    maintenance_periodic: "دورية",
    maintenance_repair: "إصلاح",
    maintenance_oil_change: "تغيير زيت",
    maintenance_tires: "إطارات",
    maintenance_brakes: "فرامل",
    maintenance_battery: "بطارية",
    maintenance_ac: "تكييف",
    maintenance_other: "أخرى",

    // Reports extras
    month: "الشهر",
    revenue: "الإيرادات",
    report: "التقرير",

    currency_symbol: "د.ت",

    // General extras
    error: "خطأ",
    all: "الكل",
    yes: "نعم",
    no: "لا",
    save_changes: "حفظ التغييرات",
    creating: "جاري الإنشاء...",
    no_results: "لا توجد نتائج",

    // Activity Log
    activity_log_title: "سجل النشاط",
    activity_log_desc: "تسجيل جميع العمليات والإجراءات",
    action: "الإجراء",
    target: "الهدف",
    user: "المستخدم",
    time: "الوقت",
    filter_by_action: "تصفية حسب الإجراء",
    filter_by_user: "تصفية حسب المستخدم",
    today: "اليوم",
    week: "الأسبوع",
    details: "التفاصيل",
    export: "تصدير",

    // Expenses
    expenses_title: "المصروفات",
    expenses_desc: "تسجيل مصاريف السيارات",
    add_expense: "تسجيل مصروف",
    edit_expense: "تعديل المصروف",
    expense_category: "نوع المصروف",
    expense_amount: "المبلغ",
    expense_date: "التاريخ",
    expense_car: "السيارة",
    fuel_cat: "وقود",
    repair_cat: "إصلاح",
    maintenance_cat: "صيانة",
    insurance_cat: "تأمين",
    tax_cat: "ضريبة",
    fine_cat: "مخالفة",
    other_cat: "أخرى",
    no_expenses: "لا توجد مصروفات",
    expense_added: "تمت إضافة المصروف",
    expense_updated: "تم تحديث المصروف",
    expense_deleted: "تم حذف المصروف",
    confirm_delete_expense: "هل أنت متأكد من حذف هذا المصروف؟",

    // Fleet
    fleet_title: "الأسطول",
    fleet_desc: "حالة السيارات ومتابعتها",
    car_status: "حالة السيارة",
    status_available: "متاحة",
    status_rented: "مؤجرة",
    status_maintenance: "صيانة",
    status_retired: "متقاعدة",
    next_maintenance_due: "الصيانة القادمة",
    no_contract: "لا يوجد عقد",
    current_client: "العميل الحالي",
    days_remaining: "الأيام المتبقية",

    // Loyalty
    loyalty_title: "برنامج الولاء",
    loyalty_desc: "نقاط ومكافآت العملاء",
    points: "النقاط",
    level: "المستوى",
    total_rents: "إجمالي الكراء",
    total_spent: "إجمالي الإنفاق",
    bronze: "برونزي",
    silver: "فضي",
    gold: "ذهبي",
    platinum: "بلاتينيوم",
    top_clients_loyalty: "أفضل العملاء",
    client_ranking: "ترتيب العملاء",
    no_loyalty_data: "لا توجد بيانات ولاء",
    next_level: "المستوى التالي",
    points_to_next_level: "نقطة للمستوى التالي",

    // Payment Status
    remaining: "المتبقي",
    paid: "مسدد",
    debt_warning: "تحذير: العميل لديه ديون سابقة",
    debt_amount: "قيمة الدين",
    client_has_debt: "هذا العميل لديه ديون غير مسددة من عقود سابقة",
    continue_despite_debt: "متابعة رغم الدين",
    select_contract: "اختر العقد",
    remaining_balance: "الرصيد المتبقي",
    total_paid: "إجمالي المدفوع",
    outstanding_debt: "ديون مستحقة",
    no_debt: "لا توجد ديون",
    date_overlap_warning: "السيارة محجوزة في هذا التاريخ",
    vehicle_tab: "السيارة",
    driver_tab: "السائق",
    driver2_tab: "سائق إضافي",
    financial_tab: "المالية",
    other_tab: "أخرى",
    contract_number: "رقم العقد",
    registration: "رقم اللوحة",
    category: "الفئة",
    fuel_type: "نوع الوقود",
    departure_date: "تاريخ الخروج",
    departure_time: "وقت الخروج",
    departure_place: "مكان الخروج",
    return_time: "وقت الرجوع",
    departure_km: "عداد الخروج",
    return_km: "عداد الرجوع",
    remise_retour: " Remise au retour",
    driver_name: "الاسم واللقب",
    driver_phone: "الهاتف",
    driver_cin: "رقم البطاقة",
    driver_cin_date: "تاريخ البطاقة",
    driver_cin_place: "مكان البطاقة",
    driver_dob: "تاريخ الميلاد",
    driver_birth_place: "مكان الميلاد",
    driver_address: "العنوان",
    driver_license_date: "تاريخ الرخصة",
    driver_license_place: "مكان الرخصة",
    has_driver2: "سائق إضافي؟",
    driver2_name: "الاسم واللقب",
    driver2_phone: "الهاتف",
    driver2_cin: "رقم البطاقة",
    driver2_cin_date: "تاريخ البطاقة",
    driver2_cin_place: "مكان البطاقة",
    driver2_dob: "تاريخ الميلاد",
    driver2_birth_place: "مكان الميلاد",
    driver2_address: "العنوان",
    driver2_license: "رقم الرخصة",
    driver2_license_date: "تاريخ الرخصة",
    driver2_license_place: "مكان الرخصة",
    total_facture: "TOTAL FACTURE",
    divers: "Divers",
    prep: "Prép",
    depot: "Dépôt",
    depot_garantie: "Dépôt de garantie",
    total_partiel: "TOTAL PARTIEL",
    total_ht: "TOTAL HT",
    tva: "TVA",
    somme: "المجموع",
    reste_a_payer: "الباقي للدفع",
    city: "مدينة الخروج",
    contract_date: "تاريخ العقد",
  },
  fr: {
    currency_symbol: "DT",
    appName: "Gestion de Location de Voitures",
    appDesc: "Système professionnel de gestion d'agence de location de voitures",
    dashboard: "Tableau de bord",
    clients: "Clients",
    cars: "Véhicules",
    contracts: "Contrats",
    payments: "Paiements",
    maintenance: "Maintenance",
    reports: "Rapports",
    settings: "Paramètres",

    add: "Ajouter",
    edit: "Modifier",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    search: "Rechercher",
    confirm: "Confirmer",
    back: "Retour",
    actions: "Actions",
    saving: "Enregistrement...",
    update: "Mettre à jour",
    save_error: "Erreur lors de l'enregistrement",
    delete_error: "Erreur lors de la suppression",

    status: "Statut",
    active: "Actif",
    completed: "Terminé",
    cancelled: "Annulé",
    available: "Disponible",
    rented: "Louée",
    maintenance_s: "Maintenance",
    retired: "Retirée",

    dashboard_title: "Tableau de bord",
    dashboard_desc: "Aperçu de l'activité de l'agence",
    active_contracts: "Contrats actifs",
    available_cars: "Véhicules disponibles",
    monthly_revenue: "Revenus du mois",
    total_clients: "Total clients",
    recent_contracts: "Derniers contrats",
    view_all: "Voir tout",
    quick_actions: "Actions rapides",
    no_contracts: "Aucun contrat pour le moment",
    alerts: "Alertes",
    no_alerts: "Aucune alerte pour le moment",

    login_title: "Connexion au tableau de bord",
    email: "Email",
    password: "Mot de passe",
    login: "Se connecter",
    login_anonymous: "Entrer comme invité",
    no_account: "Pas de compte ?",
    create_account: "Créer un compte",
    or: "Ou",

    register_title: "Créer un compte",
    register: "Créer le compte",
    confirm_password: "Confirmer le mot de passe",
    have_account: "Déjà un compte ?",

    clients_title: "Clients",
    clients_desc: "Gestion des clients",
    add_client: "Ajouter un client",
    edit_client: "Modifier le client",
    search_client: "Rechercher un client...",
    no_clients: "Aucun client trouvé",
    full_name: "Nom complet",
    phone: "Téléphone",
    cin: "CIN",
    cin_expiry: "Date d'expiration CIN",
    driver_license: "Permis de conduire",
    address: "Adresse",
    notes: "Notes",
    name: "Nom",
    client_updated: "Client mis à jour",
    client_added: "Client ajouté avec succès",
    client_deleted: "Client supprimé",
    confirm_delete_client: "Confirmer la suppression de ce client ?",
    client_detail_desc: "Détails du client",
    no_client_contracts: "Aucun contrat pour ce client",
    no_client_payments: "Aucun paiement pour ce client",

    cars_title: "Véhicules",
    cars_desc: "Gestion de la flotte automobile",
    add_car: "Ajouter un véhicule",
    edit_car: "Modifier le véhicule",
    search_car: "Rechercher un véhicule...",
    no_cars: "Aucun véhicule trouvé",
    brand: "Marque",
    model: "Modèle",
    year: "Année",
    plate: "Plaque",
    chassis: "Châssis",
    color: "Couleur",
    fuel: "Carburant",
    transmission: "Transmission",
    seats: "Places",
    doors: "Portes",
    price_per_day: "Prix/jour",
    price_per_week: "Prix/semaine",
    price_per_month: "Prix/mois",
    deposit: "Caution",
    insurance: "Expiration assurance",
    inspection: "Visite technique",
    all_status: "Tous les statuts",
    gasoline: "Essence",
    diesel: "Diesel",
    electric: "Électrique",
    hybrid: "Hybride",
    manual: "Manuelle",
    automatic: "Automatique",
    car_updated: "Véhicule mis à jour",
    car_added: "Véhicule ajouté avec succès",
    car_deleted: "Véhicule supprimé",
    confirm_delete_car: "Confirmer la suppression de ce véhicule ?",
    example_brand: "Ex: Renault",
    example_model: "Ex: Clio 4",
    dates: "Dates",

    contracts_title: "Contrats",
    contracts_desc: "Gestion des contrats de location",
    new_contract: "Nouveau contrat",
    no_contracts_found: "Aucun contrat trouvé",
    client: "Client",
    vehicle: "Véhicule",
    period: "Période",
    amount: "Montant",
    date: "Date",
    days: "jours",
    complete: "Terminer",
    start_date: "Date de début",
    end_date: "Date de fin",
    return_date: "Date de retour",
    rental_days: "Jours de location",
    total_amount: "Montant total",
    deposit_returned: "Caution retournée",
    cancel_contract: "Annuler le contrat",
    edit_contract: "Modifier le contrat",

    payments_title: "Paiements",
    payments_desc: "Suivi des paiements et cautions",
    add_payment: "Enregistrer un paiement",
    no_payments: "Aucun paiement trouvé",
    method: "Méthode",
    type: "Type",
    ref_contract: "Réf. contrat",
    cash: "Espèces",
    card: "Carte bancaire",
    transfer: "Virement bancaire",
    payment_type: "Paiement",
    deposit_type: "Caution",
    return_type: "Remboursement",

    maintenance_title: "Maintenance",
    maintenance_desc: "Gestion de la maintenance",
    add_maintenance: "Ajouter une maintenance",
    edit_maintenance: "Modifier la maintenance",
    no_maintenance: "Aucune maintenance trouvée",
    car_name: "Nom du véhicule",
    maintenance_type: "Type",
    cost: "Coût",
    garage: "Garage",
    next_maintenance: "Prochaine maintenance",
    description: "Description",

    reports_title: "Rapports",
    reports_desc: "Statistiques et analyses",
    total_revenue: "Revenus totaux",
    total_payments: "Total paiements",
    monthly_revenue_chart: "Revenus mensuels",
    monthly_payments_chart: "Paiements mensuels",
    fleet_status: "État de la flotte",
    top_clients: "Meilleurs clients",
    export_csv: "Exporter CSV",

    settings_title: "Paramètres",
    settings_desc: "Configuration du système",
    company_info: "Informations de l'entreprise",
    company_name: "Nom de l'entreprise",
    company_phone: "Téléphone",
    company_email: "Email",
    company_address: "Adresse",
    tax_rate: "Taux de taxe (%)",
    currency: "Devise",
    late_fee: "Frais de retard (jour)",
    save_settings: "Enregistrer les paramètres",
    database: "Base de données",
    connected: "Connecté à Firebase avec succès",
    version: "Version",
    mode: "Mode",
    production: "Production",
    deployment: "Déploiement",

    car_info: "Informations",
    pricing: "Tarifs",
    per_day: "Par jour",
    per_week: "Par semaine",
    per_month: "Par mois",
    maintenance_history: "Historique de maintenance",
    contract_history: "Historique des contrats",
    no_maintenance_records: "Aucun enregistrement de maintenance",
    no_contract_history: "Aucun contrat antérieur",
    car_not_found: "Véhicule introuvable",
    back_to_list: "Retour à la liste",

    client_not_found: "Client introuvable",
    client_contracts: "Contrats",
    client_payments: "Paiements",

    contract_detail: "Détails du contrat",
    contract_not_found: "Contrat introuvable",
    contract_payments: "Paiements",

    language: "Langue",
    arabic: "Arabe",
    french: "Français",

    // Sidebar
    appSubtitle: "Location de Voitures",
    light_mode: "Mode clair",
    dark_mode: "Mode sombre",
    logout: "Déconnexion",
    activity_log: "Journal d'activité",
    expenses: "Dépenses",
    fleet: "Flotte",
    loyalty: "Fidélité",

    // Register
    register_desc: "Inscrivez-vous pour accéder au système",

    // Errors
    error_occurred: "Une erreur est survenue",
    error_login_generic: "Une erreur est survenue lors de la connexion",
    error_user_not_found: "Email non enregistré",
    error_wrong_password: "Mot de passe incorrect",
    error_invalid_credential: "Email ou mot de passe incorrect",
    error_invalid_email: "Email invalide",
    error_too_many_requests: "Trop de tentatives, réessayez plus tard",
    error_password_mismatch: "Les mots de passe ne correspondent pas",
    error_password_too_short: "Le mot de passe doit contenir au moins 6 caractères",
    error_firebase_auth_not_initialized: "Firebase Auth non initialisé",
    error_email_in_use: "Email déjà utilisé",
    error_weak_password: "Mot de passe trop faible",
    error_operation_not_allowed: "L'inscription n'est pas activée dans Firebase",

    // Dashboard extras
    in_maintenance: "En maintenance",
    this_month: "Ce mois",
    manage_clients: "Gérer les clients",
    manage_cars: "Gérer les véhicules",
    insurance_expiring: "Assurance du véhicule va expirer bientôt",
    insurance_expired: "Assurance du véhicule expirée",
    inspection_expiring: "Visite technique va expirer bientôt",
    inspection_expired: "Visite technique expirée",
    contract_overdue: "Contrat en retard de retour",

    // Settings extras
    settings_saved: "Paramètres enregistrés avec succès",
    settings_save_error: "Erreur lors de l'enregistrement",
    firebase_project: "Projet Firebase",
    not_specified: "Non spécifié",
    company_name_placeholder: "Agence de location de voitures",
    company_name_required: "Nom de l'entreprise requis",
    deploy_to_vercel: "Pour déployer sur Vercel :",
    deploy_step_1: "Poussez le projet sur GitHub",
    deploy_step_2: "Connectez Vercel au repo GitHub",
    deploy_step_3: "Ajoutez les variables Firebase",
    deploy_step_4: "Déployez !",
    env_copied: "Variables copiées",
    copy_env_vars: "Copier les variables d'environnement",

    // Contract extras
    contract_created: "Contrat créé avec succès",
    contract_create_error: "Erreur lors de la création du contrat",
    contract_completed: "Contrat terminé avec succès",
    contract_updated: "Contrat mis à jour avec succès",
    contract_update_error: "Erreur lors de la mise à jour du contrat",
    contract_cancelled: "Contrat annulé avec succès",
    contract_cancel_error: "Erreur lors de l'annulation du contrat",
    contract_complete_error: "Erreur lors de la fin du contrat",
    contract_not_found_desc: "Contrat introuvable",
    contract_info: "Informations du contrat",
    complete_contract: "Terminer le contrat",
    no_payments_for_contract: "Aucun paiement pour ce contrat",
    cancel_contract_confirm: "Confirmer l'annulation de ce contrat ?",
    select_client: "Sélectionner un client",
    select_car: "Sélectionner un véhicule",
    create_contract: "Créer le contrat",
    deposit_returned_yes: "Oui",
    deposit_returned_no: "Non",

    // Payment extras
    payment_updated: "Paiement mis à jour",
    payment_added: "Paiement ajouté",
    delete_payment_confirm: "Confirmer la suppression de ce paiement ?",
    payment_deleted: "Paiement supprimé",
    edit_payment: "Modifier le paiement",
    new_payment: "Nouveau paiement",
    client_name: "Nom du client",

    // Maintenance extras
    done: "Effectuée",
    scheduled: "Planifiée",
    maintenance_updated: "Maintenance mise à jour",
    maintenance_added: "Maintenance ajoutée",
    delete_maintenance_confirm: "Confirmer la suppression de cette maintenance ?",
    maintenance_deleted: "Maintenance supprimée",
    search_maintenance: "Rechercher une maintenance...",
    select_type: "Choisir le type",
    maintenance_periodic: "Périodique",
    maintenance_repair: "Réparation",
    maintenance_oil_change: "Vidange",
    maintenance_tires: "Pneus",
    maintenance_brakes: "Freins",
    maintenance_battery: "Batterie",
    maintenance_ac: "Climatisation",
    maintenance_other: "Autre",

    // Reports extras
    month: "Mois",
    revenue: "Revenus",
    report: "Rapport",

    // General extras
    error: "Erreur",
    all: "Tous",
    yes: "Oui",
    no: "Non",
    save_changes: "Enregistrer les modifications",
    creating: "Création en cours...",
    no_results: "Aucun résultat",

    // Activity Log
    activity_log_title: "Journal d'activité",
    activity_log_desc: "Enregistrement de toutes les opérations",
    action: "Action",
    target: "Cible",
    user: "Utilisateur",
    time: "Heure",
    filter_by_action: "Filtrer par action",
    filter_by_user: "Filtrer par utilisateur",
    today: "Aujourd'hui",
    week: "Semaine",
    details: "Détails",
    export: "Exporter",

    // Expenses
    expenses_title: "Dépenses",
    expenses_desc: "Enregistrement des dépenses des véhicules",
    add_expense: "Enregistrer une dépense",
    edit_expense: "Modifier la dépense",
    expense_category: "Catégorie",
    expense_amount: "Montant",
    expense_date: "Date",
    expense_car: "Véhicule",
    fuel_cat: "Carburant",
    repair_cat: "Réparation",
    maintenance_cat: "Maintenance",
    insurance_cat: "Assurance",
    tax_cat: "Taxe",
    fine_cat: "Amende",
    other_cat: "Autre",
    no_expenses: "Aucune dépense",
    expense_added: "Dépense ajoutée",
    expense_updated: "Dépense mise à jour",
    expense_deleted: "Dépense supprimée",
    confirm_delete_expense: "Confirmer la suppression de cette dépense ?",

    // Fleet
    fleet_title: "Flotte",
    fleet_desc: "État des véhicules et suivi",
    car_status: "Statut du véhicule",
    status_available: "Disponible",
    status_rented: "Louée",
    status_maintenance: "Maintenance",
    status_retired: "Retirée",
    next_maintenance_due: "Prochaine maintenance",
    no_contract: "Aucun contrat",
    current_client: "Client actuel",
    days_remaining: "Jours restants",

    // Loyalty
    loyalty_title: "Programme de Fidélité",
    loyalty_desc: "Points et récompenses des clients",
    points: "Points",
    level: "Niveau",
    total_rents: "Total locations",
    total_spent: "Total dépensé",
    bronze: "Bronze",
    silver: "Argent",
    gold: "Or",
    platinum: "Platine",
    top_clients_loyalty: "Meilleurs clients",
    client_ranking: "Classement clients",
    no_loyalty_data: "Aucune donnée de fidélité",
    next_level: "Prochain niveau",
    points_to_next_level: "points pour le prochain niveau",

    // Payment Status
    remaining: "Restant",
    paid: "Payé",
    debt_warning: "Attention : le client a des dettes antérieures",
    debt_amount: "Montant de la dette",
    client_has_debt: "Ce client a des dettes non soldées de contrats précédents",
    continue_despite_debt: "Continuer malgré la dette",
    select_contract: "Sélectionner le contrat",
    remaining_balance: "Solde restant",
    total_paid: "Total payé",
    outstanding_debt: "Dettes impayées",
    no_debt: "Aucune dette",
    date_overlap_warning: "Ce véhicule est déjà réservé à cette date",
    vehicle_tab: "Véhicule",
    driver_tab: "Conducteur",
    driver2_tab: "2ème conducteur",
    financial_tab: "Finances",
    other_tab: "Autres",
    contract_number: "N° Contrat",
    registration: "Immatriculation",
    category: "Catégorie",
    fuel_type: "Carburant",
    departure_date: "Date de sortie",
    departure_time: "Heure de sortie",
    departure_place: "Lieu de sortie",
    return_time: "Heure de retour",
    departure_km: "Km sortie",
    return_km: "Km retour",
    remise_retour: "Remise au retour",
    driver_name: "Nom et prénom",
    driver_phone: "Téléphone",
    driver_cin: "N° CIN",
    driver_cin_date: "Date CIN",
    driver_cin_place: "Lieu CIN",
    driver_dob: "Date naissance",
    driver_birth_place: "Lieu naissance",
    driver_address: "Adresse",
    driver_license_date: "Date permis",
    driver_license_place: "Lieu permis",
    has_driver2: "2ème conducteur ?",
    driver2_name: "Nom et prénom",
    driver2_phone: "Téléphone",
    driver2_cin: "N° CIN",
    driver2_cin_date: "Date CIN",
    driver2_cin_place: "Lieu CIN",
    driver2_dob: "Date naissance",
    driver2_birth_place: "Lieu naissance",
    driver2_address: "Adresse",
    driver2_license: "N° Permis",
    driver2_license_date: "Date permis",
    driver2_license_place: "Lieu permis",
    total_facture: "TOTAL FACTURE",
    divers: "Divers",
    prep: "Prép",
    depot: "Dépôt",
    depot_garantie: "Dépôt de garantie",
    total_partiel: "TOTAL PARTIEL",
    total_ht: "TOTAL HT",
    tva: "TVA",
    somme: "Somme",
    reste_a_payer: "Reste à payer",
    city: "Ville de sortie",
    contract_date: "Date contrat",
  },
};

const LangContext = createContext<LangCtx>({
  lang: "ar",
  t: () => "",
  setLang: () => {},
});

export function useLang() {
  return useContext(LangContext);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ar");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const stored = localStorage.getItem("lang") as Lang | null;
    if (stored === "ar" || stored === "fr") {
      setLangState(stored);
      document.documentElement.lang = stored;
      document.documentElement.dir = stored === "ar" ? "rtl" : "ltr";
    } else {
      document.documentElement.lang = "ar";
      document.documentElement.dir = "rtl";
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
    document.documentElement.lang = l;
    window.location.reload();
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  if (!mounted) return <>{children}</>;

  return (
    <LangContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LangContext.Provider>
  );
}
